# Book settings
title: family-resources-survey
author: Nikhil Woodruff

repository:
  url: https://github.com/nikhilwoodruff/family-resources-survey
  branch: master
  path_to_book: docs

html:
  use_edit_page_button  : true
  use_repository_button : true
  use_issues_button     : true

# This enables plotly's JavaScript
# See https://github.com/executablebooks/jupyter-book/issues/954#issuecomment-688220038
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

execute:
  execute_notebooks: 'off'